spring.application.name=ilican-special-education-ms

#spring.datasource.url=${POSTGRES_JDBC_URL}
spring.datasource.url=jdbc:postgresql://db.fcjymkywuclsdasulzgs.supabase.co:5432/postgres?user=postgres&password=QKje30@Z
#spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.username=db.fcjymkywuclsdasulzgs.supabase.co
#spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.password=QKje30@Z

supabase.s3.endpoint=https://fcjymkywuclsdasulzgs.storage.supabase.co/storage/v1/s3
supabase.s3.region=eu-central-1
supabase.s3.bucket-name=employee-bucket

supabase.s3.access-key=5cf4303d3617e5acc9d9fee385d85c3f
supabase.s3.secret-key=78e8c5d0a273617f0cf5162efeb935a65a64b1bf2438cc1f154b6eb373d9008e

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
