spring.application.name=ilican-special-education-ms

spring.datasource.url=${POSTGRES_JDBC_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

supabase.s3.endpoint=https://fcjymkywuclsdasulzgs.storage.supabase.co/storage/v1/s3
supabase.s3.region=eu-central-1
supabase.s3.bucket-name=employee-bucket

supabase.s3.access-key=${SUPABASE_S3_ACCESS_KEY}
supabase.s3.secret-key=${SUPABASE_S3_SECRET_KEY}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
