name: Heroku Deployment

on:
  push:
    branches: [ "live" ]
  pull_request:
    branches: [ "live" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.14.15
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
    

   
