name: Heroku Deployment

on:
  push:
    branches: [ "liv" ]
  pull_request:
    branches: [ "liv" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Java 17 kurulumu
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'  # Gradle kullanıyorsan önbellekleme sağlar

      # Heroku için Java 17 ayarları (system.properties)
      - name: Set Java 17 for Heroku
        run: echo "java.runtime.version=17" > system.properties

      # Gradle ile Projeyi Build Etme (bootJar kullanarak)
      - name: Build with Gradle
        run: ./gradlew clean bootJar

      # Procfile oluştur (Heroku'nun doğru JAR dosyasını çalıştırması için)
      - name: Create Procfile
        run: |
          echo "web: java -Dserver.port=\$PORT -jar build/libs/ilican-special-education-0.0.1-SNAPSHOT.jar" > Procfile
      # Heroku CLI kurulumu
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Heroku'ya deploy işlemi
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
